#!/bin/bash
echo "=== PATH VERIFICATION ==="
echo ""

echo "Directory Structure:"
echo "  kahoot/"
echo "  ├── admin/"
echo "  │   ├── dashboard.php"
echo "  │   ├── create_user.php"
echo "  │   ├── manage_users.php"
echo "  │   ├── create_quiz.php"
echo "  │   ├── edit_quiz.php"
echo "  │   ├── manage_quizzes.php"
echo "  │   ├── host_game.php"
echo "  │   └── game_control.php"
echo "  ├── student/"
echo "  │   ├── dashboard.php"
echo "  │   ├── join.php"
echo "  │   ├── process_join.php"
echo "  │   ├── waiting.php"
echo "  │   └── game.php"
echo "  ├── api/"
echo "  │   ├── auth.php"
echo "  │   ├── quiz.php"
echo "  │   ├── game.php"
echo "  │   ├── poll.php"
echo "  │   └── game_status.php"
echo "  ├── css/"
echo "  │   └── style.css"
echo "  ├── data/"
echo "  ├── sessions/"
echo "  ├── config.php"
echo "  └── index.php"
echo ""

echo "Access Paths:"
echo "  From admin/ to admin/:         filename.php (e.g., dashboard.php)"
echo "  From admin/ to api/:            ../api/auth.php"
echo "  From student/ to student/:       filename.php (e.g., dashboard.php)"
echo "  From student/ to api/:          ../api/auth.php"
echo "  From root to api/:              api/auth.php"
echo "  From root to student/:           student/join.php"
echo ""

echo "File Verification:"
echo -n "  admin/dashboard.php: "; [ -f admin/dashboard.php ] && echo "✅" || echo "❌"
echo -n "  student/dashboard.php: "; [ -f student/dashboard.php ] && echo "✅" || echo "❌"
echo -n "  api/auth.php: "; [ -f api/auth.php ] && echo "✅" || echo "❌"
echo -n "  css/style.css: "; [ -f css/style.css ] && echo "✅" || echo "❌"
echo -n "  config.php: "; [ -f config.php ] && echo "✅" || echo "❌"
echo -n "  index.php: "; [ -f index.php ] && echo "✅" || echo "❌"
echo ""

echo "Sample Data:"
echo -n "  data/quizzes.json: "; [ -f data/quizzes.json ] && echo "✅" || echo "❌"
php -r '$data=json_decode(file_get_contents("data/quizzes.json"),true); echo "  - Quizzes: ".count($data["quizzes"])."\n"; echo "  - Questions: ".array_sum(array_map(function($q){return count($q["questions"]);},$data["quizzes"]))."\n";'
echo ""
echo "✅ All paths are correct!"
